version: '3.8'

services:
  caddy:
    build: .
    ports:
      - "5555:80" # for reverse proxy; change to 80:80 or 443:443 for standalone use
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - .:/srv
    restart: unless-stopped