name: Update Version

on: push

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Make the script executable
      run: chmod +x ./version.sh
    - name: Run version script
      run: ./version.sh